version: "2.4"

services:
  nest:
    image: 132344050580.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs/alpine:v0.0.2
    working_dir: /stool/cv-backend
    volumes:
      - ../nest:/stool/cv-backend
      - ${HOME}/.aws:/root/.aws
    container_name: stool-cv-backend
    entrypoint: ["yarn", "start:dev"]
    ports:
      - "3001:3000"
