export const NOTIFICATION_EMAIL_CONFIRMATION = 'TYPE_EMAIL_CONFIRMATION';
export const NOTIFICATION_EMAIL_TO_PERSONAL_EMAIL =
  'NOTIFICATION_EMAIL_TO_PERSONAL_EMAIL';
export const NOTIFICATION_FACEBOOK_MESSENGER =
  'NOTIFICATION_FACEBOOK_MESSENGER';
